### ISSUE TITLE
Server complains about float16 compute type.

### ISSUE THREAD

**Issue by elpidiovaldez** [collabora/WhisperLive#195]
I followed the installation instructions as closely as I could.  When I try to run the server with:

`python3 run_server.py --port 9090   --backend faster_whisper
`
...I get an error saying:

`ERROR:root:Error during new connection initialization: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
`
Google says:

```
You can set compute_type to "float32" or "int8".
With model = WhisperModel(model_path, device="cuda", compute_type="float32")

```
But this is not clear to me.  Where/how do I set the compute type? I have no idea where faster_whisper installs, or even if this is where I need to make the edit.

**Comment by makaveli10** [comment]
Hello @elpidiovaldez, could you share the device(gpu name) you use to run the server?

`float16` is should be supported on GPU, I guess you run it on a gpu that doesnt have support for `float16` for a quick fix you could set the `compute_type=float32` as suggested in server.py here:
https://github.com/collabora/WhisperLive/blob/0dfbdb2477019c55a533ae157feea0042117de49/whisper_live/server.py#L724

change it to:
```
compute_type="int8" if device == "cpu" else "float32",
```

**Comment by elpidiovaldez** [comment]
My GPU is Nvidia 1080ti

Your suggestion worked, thanks.  Actually I had found it, but it took an
hour or so rummaging through the code to find that line.

**Comment by nspitko** [comment]
This was marked as completed but I just hit this issue and had to change the server code. I didn't see a way to specify it in the server setup without editing the file (which is problematic in docker since the edits have to be re-applied every time the image is updated or rebuilt)

Is this still planned? I'm using a Tesla P40, which is certainly not a *fast* GPU but it's more than enough for simple local inference tasks where vram is the primary constraint.
