### ISSUE TITLE
Whisper-live taking same time on CPU and GPU to transcribe an audio

### ISSUE THREAD

**Issue by prem1303** [collabora/WhisperLive#204]
I am using whisper-live==0.2.1 , faster-whisper==0.10.0 and Ctranslate2==4.0.0

Transcribing a 30-second audio file currently requires the same amount of time whether processed on a CPU or GPU, approximately 2 minutes. Any guidance on enhancing GPU performance to expedite this task would be greatly valued.

**Comment by makaveli10** [comment]
https://github.com/collabora/WhisperLive/issues/201

**Comment by makaveli10** [comment]
@prem1303 which model are you using?

**Comment by makaveli10** [comment]
Glad that you could solve the issue @prem1303, feel free to post the solution here or open a Pull request if WhisperLive's code still has the problem since we are busy with other projects so, we rely on the community for this time to help us improving WhisperLive.

**Comment by alpcansoydas** [comment]
@prem1303 Can you share the solution please ? :)

**Comment by makaveli10** [comment]
@alpcansoydas @prem1303 Now that i put a thought to it. I guess it should take same amount of time no? because its real-time transcription and you process audio frames as you receive it not before that. So, if your CPU is good enough and you use a smaller size model it should be fast on both CPU and GPU. Although, that shouldnt be the case with `small`, `medium` or `large-v2/large-v3`.
